import{a as f,S as d,i as l}from"./assets/vendor-CesYmgD5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const m="57471701-99d02be1d10482722832ebff7";function h(r){return f.get("https://pixabay.com/api/",{params:{key:m,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(s=>s.data)}const i=document.querySelector(".gallery"),a=document.querySelector(".loader");console.log(i);console.log(a);const p=new d(".gallery a");function g(r){const s=r.map(t=>`<li>
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="300"/>
      </a>
      <p>${t.likes}</p>
      <p>${t.views}</p>
      <p>${t.comments}</p>
      <p>${t.downloads}</p>
    </li>`).join("");i.innerHTML=s,p.refresh()}function y(){i.innerHTML=""}function L(){a.classList.add("is-active")}function b(){a.classList.remove("is-active")}const u=document.querySelector(".form");console.log(u);u.addEventListener("submit",S);function S(r){r.preventDefault();const s=r.currentTarget.elements["search-text"].value.trim();console.log(r),s!==""&&(L(),y(),h(s).then(t=>{if(t.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!"}),r.target.reset();return}g(t.hits),r.target.reset()}).catch(()=>{l.show({message:"Sorry, there are no images matching your search query. Please try again!"}),r.target.reset()}).finally(()=>b()))}
//# sourceMappingURL=index.js.map
